<a href="https://colab.research.google.com/github/kjy-0429/NLP_2025/blob/main/%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EA%B8%B0%EB%B3%B8_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##탠서 생성 방법

In [1]:
##리스트나 배열로부터 직접 생성

import torch

tensor1d = torch.tensor([1, 2,3])
print(f'1차원 텐서: {tensor1d}')

tensor2d = torch.tensor([[1, 2,3],
[4, 5, 6]])
print(f'2차원 텐서:\n {tensor2d}')

1차원 텐서: tensor([1, 2, 3])
2차원 텐서:
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [2]:
###특수 함수로 생성

zeros_tensor = torch.zeros((3, 3))
ones_tensor = torch.ones((2,4))
full_tensor = torch.full((2, 2), 7)
# 2×2 텐서를 7로 채움

arange_tensor = torch.arange(0, 10, step=2)
# 0, 2, 4, 6, 8
linspace_tensor = torch.linspace(0, 1, steps=5)
# 0, 0.25, 0.5, 0.75, 1

print(f'zeros_tensor:\n {zeros_tensor}')
print(f'ones_tensor:\n {ones_tensor}')
print(f'full_tensor:\n {full_tensor}')
print(f'arange_tensor: {arange_tensor}')
print(f'linspace_tensor: {linspace_tensor}')

zeros_tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
ones_tensor:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
full_tensor:
 tensor([[7, 7],
        [7, 7]])
arange_tensor: tensor([0, 2, 4, 6, 8])
linspace_tensor: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [3]:
#무작위 텐서 생성

# rand: [0,1] 범위의 균일 분포
rand_tensor = torch.rand((3,3))

# randn: 평균 0, 표준 편차 1의 정규 분포
randn_tensor = torch.randn((2, 2))

print(f'rand_tensor:\n {rand_tensor}')
print(f'randn_tensor:\n {randn_tensor}')

rand_tensor:
 tensor([[0.0732, 0.3634, 0.9747],
        [0.5826, 0.8088, 0.9065],
        [0.3433, 0.8886, 0.8047]])
randn_tensor:
 tensor([[-0.1910, -0.9584],
        [-0.2957, -1.5655]])


In [4]:
#데이터 타입 설정

# float 텐서
float_tensor = torch.tensor([1,2,3], dtype=torch.float32)

# int 텐서
int_tensor = torch.tensor([1, 2,3], dtype=torch.int64)

print(f'float_tensor dtype: {float_tensor.dtype}')
print(f'int_tensor dtype: {int_tensor.dtype}')

float_tensor dtype: torch.float32
int_tensor dtype: torch.int64


In [5]:
#예시
def explore_tensor_dimensions():

# 차원별 텐서의 실제 의미와 활용법

  print("텐서 차원별 탐형을 시작합니다!")
  print("=" * 50)

  # 0차원: 스칼라(딥러닝에서 손실값 등)
  loss_value = torch.tensor(0.245)
  print(f"0차원 (스칼라): {loss_value}")
  print(" 실제 의미: 모델의 손실값")
  print(f"모양: {loss_value.shape}")
  print(f"차원 수: {loss_value.dim()}\n")

  # 1차원: 벡터(단어 임베딩, 특성 벡터 등)
  word_embedding = torch.tensor([0.2, -0.1, 0.8, 0.5])
  print(f"1차원 (벡터): {word_embedding}")
  print(" 실제 의미: '사랑'이라는 단어의 4차원 임베딩")
  print(f" 모양: {word_embedding.shape}")
  print(f" 차원 수: {word_embedding.dim()}\n")

  # 2차원: 행럴(이미지, 가중치 행럴 등)
  grayscale_image = torch.randint(0, 256, (4, 4))
  print(f"2차원 (행렬):\n{grayscale_image}")
  print(" 실제 의미: 4×4 픽셀 혹백 이미지")
  print(f"모양: {grayscale_image.shape}")
  print(f" 차원 수: {grayscale_image.dim()}\n")

  # 3차원: 컬러 이미지(높이 × 너비 × 채널)
  color_image = torch.randint(0, 256, (3, 4, 4)) # RGB 각 채널
  print(f"3차원 (컬러 이미지): 모양 {color_image.shape}")
  print(" 실제 의미: 4×4 픽셀 컬러 이미지 (RGB)")
  print(" 해석: 3개 채널 × 4높이 × 4너비")
  print(f" 차원 수: {color_image.dim( )}\n")

  # 4차원: 배치 이미(배치× 채널× 높이 × 너비)
  batch_images = torch.randint(0, 256, (2, 3, 4, 4))
  print(f"4차원 (이미지 배치): 모양 {batch_images.shape}")
  print(" 실제 의미: 2장의 4×4 컬러 이미지 묶음")
  print(" 해석: 2배치 × 3채널 × 4높이 × 4너비")
  print(f" 차원 수: {batch_images.dim()}\n")

  print("딥러닝에서 각 자원의 의미:")
  print(" @ 배치 자원: 한 번에 처리할 데이터 개수")
  print(" @ 특성 차원: 데이터의 특징 개수")
  print(" 공간 차원: 이미지의 높이, 너비")

# 실행
explore_tensor_dimensions()



텐서 차원별 탐형을 시작합니다!
0차원 (스칼라): 0.24500000476837158
 실제 의미: 모델의 손실값
모양: torch.Size([])
차원 수: 0

1차원 (벡터): tensor([ 0.2000, -0.1000,  0.8000,  0.5000])
 실제 의미: '사랑'이라는 단어의 4차원 임베딩
 모양: torch.Size([4])
 차원 수: 1

2차원 (행렬):
tensor([[230, 193,  50, 210],
        [ 92, 158, 142,  64],
        [ 49,  36, 194,  54],
        [ 68, 141, 194, 194]])
 실제 의미: 4×4 픽셀 혹백 이미지
모양: torch.Size([4, 4])
 차원 수: 2

3차원 (컬러 이미지): 모양 torch.Size([3, 4, 4])
 실제 의미: 4×4 픽셀 컬러 이미지 (RGB)
 해석: 3개 채널 × 4높이 × 4너비
 차원 수: 3

4차원 (이미지 배치): 모양 torch.Size([2, 3, 4, 4])
 실제 의미: 2장의 4×4 컬러 이미지 묶음
 해석: 2배치 × 3채널 × 4높이 × 4너비
 차원 수: 4

딥러닝에서 각 자원의 의미:
 @ 배치 자원: 한 번에 처리할 데이터 개수
 @ 특성 차원: 데이터의 특징 개수
 공간 차원: 이미지의 높이, 너비


###산술 연산

In [6]:
#기초 연산
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(f"a + b = {a + b}")
print(f"b - a = {b - a}")
print(f"a * b = {a * b}")
print(f"b / a = {b /a}")

# tensor([5, 7, 9])
# tensor([3, 3, 3])
# tensor([4, 10, 18])
# tensor([4.0000, 2.5000, 2.0000])

a + b = tensor([5, 7, 9])
b - a = tensor([3, 3, 3])
a * b = tensor([ 4, 10, 18])
b / a = tensor([4.0000, 2.5000, 2.0000])


In [7]:
#스칼라와의 연산
print(f"a + 10 = {a + 10}")
print(f"b * 2 = {b * 2}")

a + 10 = tensor([11, 12, 13])
b * 2 = tensor([ 8, 10, 12])


In [8]:
#브로드 캐스

a = torch.tensor([1, 2, 3])

b = torch.tensor([10])

# 브로드캐스팅: b가 자동으로 [10, 10, 10]으로 확장
print(f'a + b = {a + b}') # tensor([11, 12, 13])

a + b = tensor([11, 12, 13])


In [9]:
#인덱싱, 슬라이싱

tensor2d = torch.tensor([[10, 20, 30],
[40, 50, 60],
[70,80,90]])

# 특정 요소: (0,1)
print(f'tensor2d[0, 1]= {tensor2d[0, 1]}') # 20

# 행 슬라이싱: 1행부터 끝까지
print(f'tensor2d[1:, :] =\n {tensor2d[1:, :]}')

tensor2d[0, 1]= 20
tensor2d[1:, :] =
 tensor([[40, 50, 60],
        [70, 80, 90]])


In [10]:
#불리언 마스킹

mask = tensor2d > 50
print(f'mask:\n {mask}')
print(f'50보다 큰 값들: {tensor2d[mask]}')

mask:
 tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
50보다 큰 값들: tensor([60, 70, 80, 90])


In [11]:
#차원 변경
tensor_flat = torch.arange(6) # [0,1,2,3,4,5]
reshaped = tensor_flat.view(2, 3)
print(f'reshaped:\n {reshaped}')

reshaped:
 tensor([[0, 1, 2],
        [3, 4, 5]])


###고급 텐서 조작

In [12]:
#텐서 합치기

t1 = torch.tensor([1, 2,3])
t2= torch.tensor([4, 5,6])

# cat: 주어진 차원을 따라 텐서를 이어 붙임
cat_result = torch.cat((t1, t2), dim=0) # shape: (6,)
print(f'cat_result: {cat_result}')

# stack: 새 차원을 만들어 텐서를 쌓음
stack_result = torch.stack((t1, t2), dim=0) # shape: (2,3)
print(f'stack_result:\n {stack_result}')

cat_result: tensor([1, 2, 3, 4, 5, 6])
stack_result:
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [13]:
#텐서 나누기

big_tensor = torch.arange(10) # [0,1,2,3,4,5,6,7,8,9]

# split: 특정 크기씩 잘라 리스트로 반환
split_result = torch.split(big_tensor, split_size_or_sections=3)
print(f'split_result: {split_result}')

# chunk: 개수 기준으로 나눔
chunk_result = torch.chunk(big_tensor, chunks=3)
print(f'chunk_result: {chunk_result}')

split_result: (tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([9]))
chunk_result: (tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([8, 9]))


In [14]:
#차원 조작하기

matrix = torch.tensor([[1, 2, 3],
[4, 5, 6]])
transposed = matrix.t() # matrix.transpose(0, 1)
print(f'transposed:\n {transposed}')

# 3차원 예시
tensor_3d = torch.randn(2, 3, 4)
permute_result = tensor_3d.permute(2,1, 0) # 차원 순서 바꾸기

# squeeze/unsqueeze: 차원이 1인 축을 제거/추가
x = torch.tensor([[[1, 2, 3]]])
squeezed = x.squeeze ()
unsqueezed = squeezed.unsqueeze(0)

transposed:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


###텐서와 NumPy 배열 간 상호 변환

In [15]:
#NumPy 배열 → 파이토치 텐서

import numpy as np

np_arr = np.array([1,2,3])
tensor_from_np=torch.from_numpy(np_arr)
print(f'tensor_from_np: {tensor_from_np}')

tensor_from_np: tensor([1, 2, 3])


In [16]:
#파이토치 텐서 → NumPy 배열

np_from_tensor = tensor_from_np.numpy()
print(f'np_from_tensor: {np_from_tensor}')

np_from_tensor: [1 2 3]


In [17]:
#CPU 텐서와 NumPy 배열의 메모리 공유

# NumPy 배열 생성
np_arr = np.array([1, 2, 3])

# NumPy 배열을 파이토치 텐서로 변환(메모리 공유)
tensor_from_np=torch.from_numpy(np_arr)
print(f'변경 전 tensor_from_np: {tensor_from_np}')

# NumPy 배열의 첫 번째 원소 수정
np_arr[0] = 100
print(f'변경 후 tensor_from_np: {tensor_from_np}')

변경 전 tensor_from_np: tensor([1, 2, 3])
변경 후 tensor_from_np: tensor([100,   2,   3])


In [18]:
# GPU 사용 여부 확인
if torch.cuda.is_available():
  # GPU에서 텐서 생성(device='cuda')
  gpu_tensor = torch.tensor([1, 2, 3], device='cuda')
  # GPU 텐서를 CPU로 이동 후 NumPy 배열로 변환
  np_from_gpu = gpu_tensor.cpu().numpy()
  print(f'GPU 텐서 -> NumPy 배열: {np_from_gpu}')
else:
  print('CUDA를 사용할 수 없습니다. GPU가 지원되지 않는 환경입니다. ')

GPU 텐서 -> NumPy 배열: [1 2 3]


#텐서의 GPU활용

In [19]:
#GPU 확인

if torch.cuda.is_available():
  print("GPU 사용 가능!")
else:
  print("GPU를 사용할 수 없습니다. CPU 모드로 실행합니다.")

GPU 사용 가능!


In [20]:
#텐서를 GPU로 이동

# GPU 사용 가능 여부에 따라 'cuda' 또는 'cpu' 선택
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"사용할 디바이스: {device}")

# 텐서 생성 후 지정한 디바이스로 이동
x = torch.tensor([1.0, 2.0, 3.0]).to(device)
print(f"x가 위치한 디바이스: {x.device}")

사용할 디바이스: cuda
x가 위치한 디바이스: cuda:0


In [21]:
# GPU에서 생성된 텐서 ×를 CPU로 이동
x_cpu = x.cpu()
print(f'x_cpu가 위치한 디바이스: {x_cpu.device}')

x_cpu가 위치한 디바이스: cpu


#예제

In [22]:
#성능비교(예제)

import time

size = 10000 # 행렬 크기를 10,000 x10,000으로 설정

# CPU에서의 행렬 곱셈 수행
a_cpu = torch.rand((size, size))
b_cpu = torch.rand((size, size))

start_time = time.time()
_= torch.mm(a_cpu, b_cpu) # 행렬 곱셈
cpu_time = time. time() - start_time
print(f'CPU matmul time: {cpu_time}')

# GPU 사용 시: 동일한 행렬을 GPU로 이동하여 행렬 곱셈 수행
if torch.cuda.is_available():
  a_gpu = a_cpu.to(device)
  b_gpu = b_cpu.to(device)

  # GPU 연산은 비동기적이므로 연산 완료를 위해 동기화 필요
  torch.cuda.synchronize()
  start_time = time. time()
  _= torch.mm(a_gpu, b_gpu)
  torch.cuda.synchronize() # 연산 완료 후 동기화
  gpu_time = time.time() - start_time
  print(f'GPU matmul time: {gpu_time}')

CPU matmul time: 16.113563776016235
GPU matmul time: 0.6880171298980713


In [24]:
#1.텐서 생성
# torch.arange를 사용해 1부터 5까지의 정수를 담은 텐서 a와 6부터 10까지의 정수를 담은 텐서 b를 생성
a = torch.arange(1, 6) # 결과: tensor([1, 2, 3, 4, 5])
b = torch.arange(6, 11) # 걸과: tensor([ 6, 7, 8, 9, 10])

#2.기본 민산
# 텐서 a와 b의 원소별 덧셈과 곱샘을 수행한다.
# 결과: tensor([ 7, 9, 11, 13, 15])
# 걸과: tensor([ 6, 14, 24, 36, 50])

print(f"a + b = {a + b}")
print(f"a * b = {a * b}")

#3.브로드캐스팅
#텐서 c는 (3,1) 형태로 생성되며, 텐서 d는 (3,) 형태이다.
# 두 텐서를 더하면 브로드캐스딩 규칙에 따라 d가 (3,1)로 확장되어 (3,3) 형타의 결과가 생성된다.
c= torch. tensor([[1], [2], [3]]) # shape: (3,1)
d= torch.tensor([10, 20, 30])
print(f"브로드캐스팀 c + d:\n {c + d}")

# 4. NumPy 비교
# 텐서 a와 b를 NunPy 배열로 변환한 후 동일한 연산을 수행하여 결과를 비교한다.
np_a = a.numpy()
np_b = b.numpy()
np_result = np_a + np_b
pt_result = a + b
print(f"NumPy 덧셈 결과: {np_result}")
print(f"PyTorch 덧셈 결과: {pt_result}")

pt_result = a + b

# 5. GPU 성능 비교(선택)
# 만약 GPU가 사용할 수 있으면 대규모 행럴 곱셈을 통해 CPU와 GPU 연산 시간을 비교한다.
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 크기가 큰 랜덤 텐서 생성(10,000×10,000)
x_cpu = torch.randn((10000, 10000))
y_cpu = torch.randn((10000, 10088))

# CPU에서의 행렬 곱셈 연산 시간 측정
start = time.time()
_= torch.mm(x_cpu, y_cpu)
cpu_time = time.time() - start
print(f"CPU matmul time: {cpu_time :.4f}sec")

# GPU가 사용할 수 있는 경우 동일한 연산을 GPU에서 수행한다.
# 생성한 덴서를 GPU로 이동
x_gpu = x_cpu.to(device)
y_gpu = y_cpu.to(device)

# GPU 연산은 비동기적으로 수청되므로 걸과 측정을 위해 동기화한다.
torch.cuda.synchronize()
start = time. time()
_= torch.mm(x_gpu, y_gpu)
torch.cuda.synchronize()
gpu_time = time.time() - start
print(f"GPU matmul time: {gpu_time :.4f}sec")

a + b = tensor([ 7,  9, 11, 13, 15])
a * b = tensor([ 6, 14, 24, 36, 50])
브로드캐스팀 c + d:
 tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])
NumPy 덧셈 결과: [ 7  9 11 13 15]
PyTorch 덧셈 결과: tensor([ 7,  9, 11, 13, 15])
CPU matmul time: 17.3328sec
GPU matmul time: 0.5352sec
